### ISSUE TITLE
Very Slow Compile?

### ISSUE THREAD

**Issue by satyabikash** [bene837/af2seq#6]
2024-10-15 10:22:48.675191: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55] 
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module jit_alphafold_fn.165
********************************

showing the above, still working and predicting sequences but taking hours for 500 iterations.

>>> print(tf.config.list_physical_devices('GPU'))
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
>>> print(jax.lib.xla_bridge.get_backend().platform)
gpu

why is it showing the above warning?
and also in general how much time it should take for a protein having 150 aas for 500 iterations in an a100 gpu?

**Comment by 1ut** [comment]
@satyabikash 
Is there any update on this issue?
I'm also curious about how much time it takes to run the whole iterations.

**Comment by satyabikash** [comment]
@1ut 
No I haven't made any progress or got any update from the developers.

**Comment by Lisa-Phan** [comment]
Hello, 

I'm observing the same error. In my case, the gradient descend optimization does not run and fail after sending the message about slow compile. This happens on both both cpu and a100 gpu environment. If you have any recommendations on how to fix it, please let me know. 

'''
2025-03-31 23:58:14.556343: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55] 
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module jit_alphafold_fn.117457
********************************
  0%|                                                                                                 | 0/500 [05:41<?, ?it/s]Traceback (most recent call last):
  File "gradient_desc.py", line 33, in <module>
    d.design(target,
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/af2seq/design/core.py", line 449, in design
    sequence, loss, highest_confidence_result, feat, plddt, ptm = self.step(alphafold_model, gt_dict)
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/af2seq/design/core.py", line 831, in step
    highest_confidence_result, ptm, plddt, loss = self._calc_scores(result, feat, loss)
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/af2seq/design/core.py", line 536, in _calc_scores
    TM_aligned_mean, RMSD_aligned_mean = extract_metrics(result, feat, self.target_file)
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/af2seq/design/utils.py", line 263, in extract_metrics
    TM_aligned, RMSD_aligned = score_alignment(feat, result0, target_file)
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/af2seq/design/utils.py", line 242, in score_alignment
    alignment = tmscoring.TMscoring(
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/tmscoring/tmscore.py", line 31, in __init__
    self._load_data_index(chain_1, chain_2)
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/tmscoring/tmscore.py", line 287, in _load_data_index
    coord1 = np.hstack(coord1).astype(DTYPE, copy=False)
  File "<__array_function__ internals>", line 5, in hstack
  File "/work/09069/dhp563/miniconda_installation_20230606/envs/af2seq_new/lib/python3.8/site-packages/numpy/core/shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
'''

**Comment by riiichardh** [comment]
Hi @satyabikash 
How was it? Have you made it faster?
